version: "3.8"
services:
  app:
    build: 
      context: ./app
      args:
        - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    links:
      - "db"
    env_file:
      - .env
    ports:
      - "$FLASKPORT:$FLASKPORT"
      - "80:80"
    depends_on:
      - db
  db:
    image: mysql:5.7
    env_file:
      - .env
    ports:
      - "$SQLPORT:3306"

    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DB
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:rw