version: "3.8"
services:
  app:
    build: 
      context: ./app
    links:
      - "db"
    env_file:
      - .env
    ports:
      - "$FLASKPORT:$FLASKPORT"
      - "$EXPOSEPORT:80"
  db:
    image: mysql:5.7
    env_file:
      - .env
    ports:
      - "$SQLPORT:$SQLPORT"
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DB
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_TCP_PORT: $SQLPORT
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:rw